name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      workingDir: ./Services

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.8
    - name: Install dependencies
      working-directory: ${{env.workingDir}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.workingDir}}
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ${{env.workingDir}}
      run: dotnet test --no-restore --verbosity normal
